### ISSUE TITLE
ImportError for import porespy as ps

### ISSUE THREAD

**Issue by catastropiyush** [Sohl-Dickstein/fractal#2]
Thank you for sharing the notebook. Its really an insightful paper. I was trying to run the notebook **the_boundary_of_neural_network_trainability_is_fractal.ipynb**  but  when I try to run the command 
```
!pip install git+https://github.com/PMEAL/porespy.git
import porespy as ps
```
this error pops up.
```
---------------------------------------------------------------------------

ImportError                               Traceback (most recent call last)

[<ipython-input-7-f28eedeafd48>](https://localhost:8080/#) in <cell line: 3>()
      1 ## tool for computing fractal dimension
      2 get_ipython().system('pip install git+https://github.com/PMEAL/porespy.git')
----> 3 import porespy as ps

6 frames

[/usr/local/lib/python3.10/dist-packages/porespy/metrics/_regionprops.py](https://localhost:8080/#) in <module>
      6 from skimage.measure import mesh_surface_area, regionprops
      7 from skimage.measure._regionprops import RegionProperties
----> 8 from skimage.morphology import ball, skeletonize_3d
      9 
     10 from porespy.tools import bbox_to_slices, extract_subsection

ImportError: cannot import name 'skeletonize_3d' from 'skimage.morphology' (/usr/local/lib/python3.10/dist-packages/skimage/morphology/__init__.py)
```
I tried to upgrade scikit `!pip install scikit-image --upgrade` but the error persists.

Thank you for your time

**Comment by wanhanbo** [comment]
> Thank you for sharing the notebook. Its really an insightful paper. I was trying to run the notebook **the_boundary_of_neural_network_trainability_is_fractal.ipynb** but when I try to run the command
> 
> ```
> !pip install git+https://github.com/PMEAL/porespy.git
> import porespy as ps
> ```
> 
> this error pops up.
> 
> ```
> ---------------------------------------------------------------------------
> 
> ImportError                               Traceback (most recent call last)
> 
> [<ipython-input-7-f28eedeafd48>](https://localhost:8080/#) in <cell line: 3>()
>       1 ## tool for computing fractal dimension
>       2 get_ipython().system('pip install git+https://github.com/PMEAL/porespy.git')
> ----> 3 import porespy as ps
> 
> 6 frames
> 
> [/usr/local/lib/python3.10/dist-packages/porespy/metrics/_regionprops.py](https://localhost:8080/#) in <module>
>       6 from skimage.measure import mesh_surface_area, regionprops
>       7 from skimage.measure._regionprops import RegionProperties
> ----> 8 from skimage.morphology import ball, skeletonize_3d
>       9 
>      10 from porespy.tools import bbox_to_slices, extract_subsection
> 
> ImportError: cannot import name 'skeletonize_3d' from 'skimage.morphology' (/usr/local/lib/python3.10/dist-packages/skimage/morphology/__init__.py)
> ```
> 
> I tried to upgrade scikit `!pip install scikit-image --upgrade` but the error persists.
> 
> Thank you for your time

I have the same problem, did you solve it?

**Comment by catastropiyush** [comment]
@wanhanbo no I still haven't. will try again tomorrow.

**Comment by lubarbosa** [comment]
Hi @catastropiyush any progress here? Facing the same thing, tried to downgrade scikit-image but not work on python 3.10+

**Comment by catastropiyush** [comment]
@lubarbosa I ran again the notebook and I get this error ---------------------------------------------------------------------------
```
AttributeError                            Traceback (most recent call last)
[<ipython-input-6-f28eedeafd48>](https://localhost:8080/#) in <cell line: 0>()
      1 ## tool for computing fractal dimension
      2 get_ipython().system('pip install git+https://github.com/PMEAL/porespy.git')
----> 3 import porespy as ps

11 frames
[/usr/local/lib/python3.11/dist-packages/numpy/core/numeric.py](https://localhost:8080/#) in <module>
   2518 from .fromnumeric import *
   2519 from . import arrayprint
-> 2520 from .arrayprint import *
   2521 from . import _asarray
   2522 from ._asarray import *

AttributeError: partially initialized module 'numpy.core.arrayprint' has no attribute 'array2string' (most likely due to a circular import)
```

But I am able to make the initial plots. Working on the animations.

![Image](https://github.com/user-attachments/assets/9eb90267-844f-4b2b-b408-2c181a595213)
